name: Build mkosi Image

on:
  workflow_dispatch:
    inputs:
      distro:
        description: 'Desired distribution'
        required: true
        type: choice
        options:
          - fedora
          - debian
          - ubuntu
          - arch
          - opensuse
          - mageia
          - centos
          - rhel
          - rhel-ubi
          - openmandriva
          - rocky
          - alma
      compression:
        description: 'Compression method'
        required: true
        type: choice
        options:
          - zstd
          - gzip
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: setup-mkosi
      uses: systemd/mkosi@v25.3

    - name: Prepare mkosi build
      run: |
        mkdir -p ${{ github.workspace }}/mkosi_build
        cp configs/${{ inputs.distro }}.conf ${{ github.workspace }}/mkosi_build/${{ inputs.distro }}.conf

    - name: Build mkosi image for ${{ inputs.distro }}
      run: |
        cd ${{ github.workspace }}//mkosi_build
        mkosi --distribution ${{ inputs.distro }} --include ${{ github.workspace }}/mkosi_build/${{ inputs.distro }}.conf --format oci --compress-output ${{ inputs.compression }} build

    # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
    # https://github.com/macbre/push-to-ghcr/issues/12
    - name: Lowercase Actor
      id: actor_case
      uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
      with:
        string: ${{ github.actor }}

    - name: Install Skopeo
      run: sudo apt-get install -y skopeo

    - name: Upload OCI to GHCR
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
        sudo skopeo copy oci:${{ github.workspace }}/mkosi_build/image docker://ghcr.io/${{ steps.actor_case.outputs.lowercase }}/${{ inputs.distro }}:latest
